"""recalibration log

Revision ID: 0004_recalibration_log
Revises: 0003_decision_outcome
Create Date: 2026-06-17
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0004_recalibration_log"
down_revision: Union[str, None] = "0003_decision_outcome"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recalibration_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('good_count', sa.Integer(), nullable=False),
    sa.Column('bad_count', sa.Integer(), nullable=False),
    sa.Column('mean_score_good', sa.Float(), nullable=True),
    sa.Column('mean_score_bad', sa.Float(), nullable=True),
    sa.Column('separation', sa.Float(), nullable=True),
    sa.Column('recommended_cutoff', sa.Float(), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('weights_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recalibration_log')
    # ### end Alembic commands ###
